name: stark
description: Stark - a pragmatic lightweight dependency injection framework for Dart
version: 3.0.5
author: Diefferson Santos <diefferson.sts@gmail.com>
homepage: https://github.com/diefferson/stark

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
